AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template provisions API Gateway's RestApi from Swagger.yaml.
  (If Swagger.yaml and $S3_SWAGGER_BUCKET_NAME parameter of ecs-cicd are specified).
Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Tags:
        - Key: CloudFormation
          Value: true
      Name: GITHUB_REPO
      Body:
OPEN_API_SPEC

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: 'Deployed API'
      RestApiId: !Ref ApiGateway

  Prod:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      Variables:
        Stack: Prod
      