AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template provisions ECS service/task, ALB, API Gateway (optional), EFS (optional), Scaling Policy, Alarms, and Logging.

Parameters:
  Tag:
    Type: String
    Description: Tag of the Docker Image.
    Default: IMAGE_TAG
  ContainerPort:
    Type: Number
    Default: 9000
    Description: What port number the application inside the docker container is binding to
  EnvironmentName:
    Type: String
    Description: Name of the Environment.
    Default: ENVIRONMENT_NAME
  ServiceMaxCapacity:
    Description: 'The maximum number of simultaneous tasks, that you want to run on the cluster.'
    Type: Number
    Default: 5
    ConstraintDescription: 'Must be >= 1'
    MinValue: 1
  ServiceMinCapacity:
    Description: 'The minimum number of simultaneous tasks, that you want to run on the cluster.'
    Type: Number
    Default: 2
    ConstraintDescription: 'Must be >= 1'
    MinValue: 1
  Email:
    Type: String
    Description: Email address to notify when an API activity has triggered an alarm
    Default: EMAIL
  ECSRepositoryName:
    Type: String
    Description: 'ECS Repository Name'
    Default: ECS_REPOSITORY_NAME

Conditions:
  IsApiGatewayNeeded: !Not [ !Equals [ 'S3_SWAGGER_BUCKET_NAME', 'SKIP_API_GATEWAY' ] ]

Resources:
  
  # The task definition. This is a simple metadata description of what
  # container to run, and what resource requirements it has.
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      #The Family name will be used along with ECS_CLUSTER_NAME to prepare the stack name. It should be of Format abb-cdd-sd
      Family: APP_NAME-BUILD_SCOPE
      Cpu: ECS_CPU_COUNT
      Memory: ECS_MEMORY_RESERVATION_COUNT
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-ECSTaskExecutionRoleArn'
      # TODO: too much power for the task
      TaskRoleArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-ECSTaskExecutionRoleArn'
      ContainerDefinitions:
      - Name: xray-sidecar
        # TODO: it is expected that you have xray-daemon in your ECR
        Image: "amazon/aws-xray-daemon:3.2.0"
        PortMappings:
          - ContainerPort: 2000
            Protocol: udp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'ContainerLogGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: !Sub "${EnvironmentName}-APP_NAME"
      - Name: APP_NAME
        Essential: 'true'
        Image:
          "Fn::Sub":
            - '${AccountId}.dkr.ecr.${Region}.amazonaws.com/${ECSRepositoryName}:TAG'
            - { AccountId: { "Ref" : "AWS::AccountId" }, Region: { "Ref" : "AWS::Region" }}
        Ulimits:
          - Name: nofile
            SoftLimit: 2048
            HardLimit: 8192
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'ContainerLogGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: !Sub "${EnvironmentName}-APP_NAME"
        PortMappings:
          - ContainerPort: !Ref 'ContainerPort'
        Environment:
ENVIRONMENT_VARIABLES

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSServicePolicy
    Properties:
      Cluster:
        Fn::ImportValue: !Sub '${EnvironmentName}-ECSCluster'
      LaunchType: FARGATE
      DesiredCount: DESIRED_COUNT
      TaskDefinition: !Ref 'TaskDefinition'
      LoadBalancers:
        - ContainerName: APP_NAME
          ContainerPort: !Ref 'ContainerPort'
          TargetGroupArn: !Ref 'TargetGroup'
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue: !Sub '${EnvironmentName}-ECSHostSecurityGroup'
          Subnets:
            - Fn::ImportValue: !Sub '${EnvironmentName}-PrivateSubnet1'
            - Fn::ImportValue: !Sub '${EnvironmentName}-PrivateSubnet2'
      # TODO: Looks like it is not necessary for Fargate?
      # Role: !Ref 'ECSServiceRole'


  # A target group. This is used for keeping track of all the tasks, and
  # what IP addresses / port numbers they have. You can query it yourself,
  # to use the addresses yourself, but most often this target group is just
  # connected to an application load balancer, or network load balancer, so
  # it can automatically distribute traffic across all the targets.
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: !Sub '${EnvironmentName}-APP_NAME'
      Port: !Ref 'ContainerPort'
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPC'

  # Create a rule on the load balancer for routing traffic to the target group
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: host-header
          Values:
          - 'APP_NAME.DOMAIN_NAME'
      ListenerArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-PublicListener'
      # The priority for the routing rule added to the load balancer.
      # This only applies if your have multiple services which have been
      # assigned to different paths on the load balancer
      Priority: ECS_LISTENER_PRIORITY

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Security Group
      VpcId:
        Fn::ImportValue:
          !Sub '${EnvironmentName}-VPC'
      SecurityGroupIngress:
        # Only allow inbound access to ECS from the same VPC
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
  ContainerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '${EnvironmentName}-APP_NAME'
      RetentionInDays: 14
#  ALB:
#    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
#    Properties:
#      Name: !Sub "${EnvironmentName}-APP_NAME"
#      Scheme: internet-facing
#      LoadBalancerAttributes:
#        - Key: idle_timeout.timeout_seconds
#          Value: '30'
#      Subnets:
#        - Fn::ImportValue: !Sub '${EnvironmentName}-PublicSubnet1'
#        - Fn::ImportValue: !Sub '${EnvironmentName}-PublicSubnet2'
#      SecurityGroups:
#      - Ref: ECSSecurityGroup
#      - Fn::ImportValue: !Sub '${EnvironmentName}-ECSHostSecurityGroup'
#  ALBListener:
#    Type: AWS::ElasticLoadBalancingV2::Listener
#    DependsOn: ECSServiceRole
#    Properties:
#      Certificates:
#      - CertificateArn: CERTIFICATE_ARN
#      DefaultActions:
#      - Type: forward
#        TargetGroupArn:
#          Ref: TargetGroup
#      LoadBalancerArn:
#        Ref: ALB
#      Port: '443'
#      Protocol: HTTPS
#  TargetGroup:
#    Type: AWS::ElasticLoadBalancingV2::TargetGroup
#    DependsOn: ALB
#    Properties:
#      Name: !Sub "${EnvironmentName}-APP_NAME"
#      HealthCheckIntervalSeconds: 10
#      HealthCheckPath: /health
#      HealthCheckProtocol: HTTP
#      HealthCheckTimeoutSeconds: 5
#      HealthyThresholdCount: 2
#      TargetType: ip
#      Port: !Ref 'ContainerPort'
#      Protocol: HTTP
#      UnhealthyThresholdCount: 2
#      VpcId:
#        Fn::ImportValue: !Sub '${EnvironmentName}-VPC'
  Route53:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: HOSTED_ZONE
      Comment: APP_NAME target
      RecordSets:
      - Name: APP_NAME.HOSTED_ZONE
        Type: A
        AliasTarget:
          HostedZoneId:
            Fn::ImportValue: !Sub '${EnvironmentName}-PublicLoadBalancerHostedZoneID'
          DNSName:
            Fn::ImportValue: !Sub '${EnvironmentName}-PublicLoadBalancerDNSName'
  ECSServicePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ecs-service"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ['*']
            Resource: '*'
      Roles:
      - Ref: ECSServiceRole
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Condition: IsApiGatewayNeeded
    Properties:
      Name: GITHUB_REPO
      Body:
OPEN_API_SPEC
  ScalableTargetRole: # based on http://docs.aws.amazon.com/AmazonECS/latest/developerguide/autoscale_IAM_role.html
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'application-autoscaling.amazonaws.com'
          Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: ecs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'ecs:DescribeServices'
            - 'ecs:UpdateService'
            Resource: '*'
      - PolicyName: cloudwatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'cloudwatch:DescribeAlarms'
            Resource: '*'
  ScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: !Ref ServiceMaxCapacity
      MinCapacity: !Ref ServiceMinCapacity
      ResourceId: !Sub
        - 'service/${Cluster}/${Service}'
        - Cluster:
            'Fn::ImportValue': !Sub '${EnvironmentName}-ECSCluster'
          Service: !GetAtt 'Service.Name'
      RoleARN: !GetAtt 'ScalableTargetRole.Arn'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
  ScaleUpPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Sub '${AWS::StackName}-scale-up'
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 300
        MinAdjustmentMagnitude: 1
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 25
  ScaleDownPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Sub '${AWS::StackName}-scale-down'
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 300
        MinAdjustmentMagnitude: 1
        StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -25
  CPUUtilizationHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Service is running out of CPU'
      Namespace: 'AWS/ECS'
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-ECSCluster'
      - Name: ServiceName
        Value: !GetAtt 'Service.Name'
      MetricName: CPUUtilization
      ComparisonOperator: GreaterThanThreshold
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 80
      AlarmActions:
      - !Ref ScaleUpPolicy
  CPUUtilizationLowAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Service is wasting CPU'
      Namespace: 'AWS/ECS'
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-ECSCluster'
      - Name: ServiceName
        Value: !GetAtt 'Service.Name'
      MetricName: CPUUtilization
      ComparisonOperator: LessThanThreshold
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 20
      AlarmActions:
      - !Ref ScaleDownPolicy
  MemoryUtilizationHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Service is running out of memory'
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-ECSCluster'
      - Name: ServiceName
        Value: !GetAtt 'Service.Name'
      MetricName: MemoryUtilization
      ComparisonOperator: GreaterThanThreshold
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 80
      AlarmActions:
      - !Ref ScaleUpPolicy
  MemoryUtilizationLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Service is wasting memory'
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-ECSCluster'
      - Name: ServiceName
        Value: !GetAtt 'Service.Name'
      MetricName: MemoryUtilization
      ComparisonOperator: LessThanThreshold
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 20
      AlarmActions:
      - !Ref ScaleDownPolicy
  HealthyHostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'ECS APP_NAME - Healthy Hosts ${EnvironmentName}'
      EvaluationPeriods: 5
      Statistic: Maximum
      Threshold: '1'
      AlarmDescription: Alarm if the number of healthy hosts is less than or equal to 1.
      Period: '300'
      AlarmActions:
      - Ref: "AlarmNotificationTopic"
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-PublicLoadBalancerFullName'
      - Name: TargetGroup
        Value:
          "Fn::GetAtt": [ TargetGroup, TargetGroupFullName ]
      ComparisonOperator: LessThanThreshold
      MetricName: HealthyHostCount
  UnhealthyHostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'ECS APP_NAME - Unhealthy Hosts ${EnvironmentName}'
      EvaluationPeriods: 5
      Statistic: Maximum
      Threshold: '1'
      AlarmDescription: Alarm if the number of unhealthy hosts is greater than or equal to 1.
      Period: '300'
      AlarmActions:
      - Ref: "AlarmNotificationTopic"
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value:
          Fn::ImportValue: !Sub '${EnvironmentName}-PublicLoadBalancerFullName'
      - Name: TargetGroup
        Value:
          "Fn::GetAtt": [ TargetGroup, TargetGroupFullName ]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: UnHealthyHostCount
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'APP_NAME-topic-${EnvironmentName}'
  AlarmNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: EMAIL
      Protocol: email
      TopicArn:
        Ref: AlarmNotificationTopic
Outputs:
  ecsservice:
    Value:
      Ref: Service
  AppALBDNS:
    Value:
      Fn::ImportValue: !Sub '${EnvironmentName}-PublicLoadBalancerDNSName'
